### ISSUE TITLE
ac-sources-semantic can not work since the commit of Jan 17, 2015

### ISSUE THREAD

**Issue by zijianyue** [auto-complete/auto-complete#377]
The completion after . or  -> can not pop up now .

**Comment by m2ym** [comment]
What do you see when `M-x ac-complete-semantic` after `.` or `->`?

**Comment by zijianyue** [comment]
ac-complete-semantic works OK, but auto-complete can not work when there is ac-source-semantic in ac-sources.

**Comment by m2ym** [comment]
Okay, I'll looking into this.

**Comment by mikefaille** [comment]
Auto-complete don't work since few days. I don't know why. Maybe, I have this issue... How can I verify ?

**Comment by m2ym** [comment]
@mikefaille `M-x ac-complete-semantic` after `.` or `->` works?

**Comment by mikefaille** [comment]
Hum, I just have trouble with auto-complete since few days only even with "ac-set-trigger-key". I begin with emacs since 2 months (just to explain i'm a beginner).

Anyways, when I see  «can not work since the commit of Jan 17, 2017», it's why I have the temptation to follow up this issue.

«M-x ac-complete-semantic after . or -> works?»
I don't have this issue. Sorry. Maybe I will just create a new bug report.

**Comment by m2ym** [comment]
By #388, this issue seems to be solved.

**Comment by zijianyue** [comment]
it works now ,thanks
