### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by tarsius** [auto-complete/auto-complete#509]
[`auto-complete`](https://github.com/auto-complete/auto-complete), [`popup-el`](https://github.com/auto-complete/popup-el) and [`fuzzy-el`](https://github.com/auto-complete/fuzzy-el) are looking for new maintainers.  If you are interested, then please say so.

Currently I am the "owner" of these repositories but I have only volunteered to do that so that these packages can be handed over smoothly once we have found some volunteers. I am not qualified myself because I have never even just *used* these packages.

**Comment by dickmao** [comment]
You can add me.

**Comment by NotMoni** [comment]
@tarsius Hey mate, I currently maintain Node-Fetch and would be happy to help. You can count me in. 🦄

**Comment by tarsius** [comment]
Hey @dickmao and @NotMoni, thanks for offering your help!

Could you please say a few words about your experience maintaining elisp packages and also what kind of help you can and intend to offer here.

I intend to review all commits for a while at least. Past experience has shown that I might have to intervene occasionally but I'll try hard to stay out of your way.

**Comment by NotMoni** [comment]
Hey, @tarsius I am a nodeJS dev, but i can review basic pr and common issues.

**Comment by tarsius** [comment]
@NotMoni I was really hoping for an experienced elisp developer but issue triage is also useful.

You already have the necessary permissions, feel free to begin work. :grin: 

I had a quick look and feel that many old issues can be closed. It's probably best if you provide a one sentence for why you close an issue, except in extreme cases such as #481.

**Comment by dickmao** [comment]
I sent emails to the address listed on your github profile, and I suspect they went to spam.

Could you re-extend the Collaborator invite?  The first one seems to have expired.

**Comment by dickmao** [comment]
Thanks.  I generally work best with full Admin access, however.

**Comment by tarsius** [comment]
> I sent emails to the address listed on your github profile, and I suspect they went to spam.

I got your messages but I did not fully understand your first message and was a bit busy at the time so I put of replying. I understood what you said (I believe) but I was confused as to whether that meant that you did *not* want help maintain `auto-complete` after all. You had also let the invitation to this repo run out by then so I assumed that that was what it meant.

You talked about the value you see in `auto-complete` and how it relates to `company-mode`. This is of interest to other people as well, since they might want to know how the maintainers feel about the package. I think you should post that or something similar here.

**Comment by tarsius** [comment]
> Thanks. I generally work best with full Admin access, however.

I would like to wait with that for a while and review all changes. In the past I have given more far reaching access right away and that did not always work out so well.

**Comment by tarsius** [comment]
You are not closing *every* issue right now, are you?

**Comment by dickmao** [comment]
> You are not closing every issue right now, are you?

No, some cling to relevancy, but just barely.

**Comment by tarsius** [comment]
You should have discussed this with me first. I would have asked you to use a less aggressive (close fewer issues), more careful  (spend more time investigating each issue, twenty seconds is not enough), and more explicit (above I already asked for a short explanation in *most* cases) approach.

**Comment by asmeurer** [comment]
I agree. Several issues I was following were closed without explanation, or simply because "I don't plan to work on this" (but why not just leave them open in case someone else does?).

**Comment by dickmao** [comment]
I'll reopen the issues.

**Comment by tarsius** [comment]
No, it's okay.

I would probably have closed the majority of these issues myself but I would have provided a short justification in more cases. Closing many issues wasn't necessarily wrong considering that past maintainers have done a very bad job closing resolved issues and issues that are certain not to lead anywhere.

A few of these issues shouldn't have been closed, but now that they are closed we can leave them closed. Reopening issues that should remain closed also wouldn't be desirable.

If someone feels that a *particular* issues should be reopened, then they just have to ask.

**Comment by tarsius** [comment]
@dickmao **I just told you to NOT reopen the issues.**

**Comment by dickmao** [comment]
Very sorry!  I didn't get your message in time!

Well, I guess we're in no worse a state than we were four hours ago.

**Comment by tarsius** [comment]
> Very sorry! I didn't get your message in time!

This is now the second time that you just acted without giving someone else *a few minutes* to react first. You might want to avoid that in the future.

> Well, I guess we're in no worse a state than we were four hours ago.

I disagree. This is worse than a few hours ago. Going forward I will not only hesitate to give someone write access but even just triage rights. 

Well, I think this is goodby. This and #510 does not look like this project is going to get any useful contributions from you. I feel a bit bad saying it like this but I don't want to waste any time on this either.

**Comment by NotMoni** [comment]
@dickmao Bto chilll 😐

**Comment by jcs090218** [comment]
@tarsius Can I maintain `popup.el`? Since my config and some of my packages are rely on this package, I would like to maintain this package to just in case it doesn't break in the future and also keep the package as stable as possible! Thanks! :)

**Comment by tarsius** [comment]
I've invited you to the organization. Once you have accepted that I can assign you to the repository.

**Comment by jcs090218** [comment]
Joined! Thanks for the invite! :)

**Comment by jcs090218** [comment]
I may have time for this package now! I am not too confident to maintain this package since the code base is quite complicated and not modular. But I would still like to give this package a try, and maybe start reading some code base and do basic review PRs; answering issue, etc.

@tarsius Can you assign me to this repo? Thanks! 😁

**Comment by jcs090218** [comment]
@tarsius Ping! You there? :)

**Comment by tarsius** [comment]
Slightly busy.

I've given you access now.

**Comment by jcs090218** [comment]
Thanks! Sorry for pinging you while you are busy!

**Comment by tarsius** [comment]
Naaa, that's okay.

**Comment by tarsius** [comment]
@NotMoni are you actually doing any triaging? Asking because you have the rights to do so. :wink:

**Comment by esac-io** [comment]
Hi, Can you add me ?

**Comment by tarsius** [comment]
@jcs090218 I just made you a maintainer of the other two repositories (fuzzy and the webpage).

**Comment by jcs090218** [comment]
Ah, okay! Thanks! :)

**Comment by NotMoni** [comment]
> @NotMoni are you actually doing any triaging? Asking because you have the rights to do so. 😉

Hey, I've had some other major changes in my life. I won't be able to triage, you can remove me. Sorry.

**Comment by tarsius** [comment]
@NotMoni No problem. All the best to you!

**Comment by tarsius** [comment]
Hey @jcs090218,

By mail @piotrklibert volunteered to become another maintainer. He doesn't have experience maintaining elisp packages but otherwise has a lot of experience with lisps and such. I think he would make a nice addition to the team. I told him it would be best to work with pull-requests initially but am inclined to give him commit access soon. But of course since nowadays you do all the work around here you get to decide how we proceed.

**Comment by jcs090218** [comment]
Sounds good to me!

TBH, I have less and less activities for this package nowadays. It's always great to have people step up as a co-maintainer. :)

**Comment by piotrklibert** [comment]
Hello guys, nice to meet you! 

First, I wrote my mail before I read this thread to the bottom... That was a mistake - I didn't know that the maintainer was already decided, so I wrote that I would like to be one. I tried to sound confident, but to be honest, I wasn't 100% sure I could do it, as I have no experience with maintaining popular open-source packages - none at all. I was also worried about how much time I'll be able to reserve for the project. I think becoming a co-maintainer (instead of a sole maintainer) will help on both fronts, so I'm delighted that you consider me for that position :)

With that out of the way: I'm currently sick, but getting better already, so I think I'll be able to set a few h aside during the weekend. Where should I start? I have a few immediate itches I'd like to scratch, but I need to do some research before taking care of them. I can help with whatever is needed the most in the meantime :)

Finally, there's a link to my blog in my profile - a quick glance should give you (@jcs090218) an overview of what I'm interested in and what I happened to work on (outside of my day job, I mean). I'll also happily answer if you have any questions! :)

**Comment by jcs090218** [comment]
I reckon there are not too many things to do since this package has been inactive for such a long time (4 to 5 years?). I am only baby sit the package by fixing basic bugs and make sure it compatible to newer version of Emacs, etc.

I don't think we are going to continue develop this package, so anything else like read through the code and improve the documentation may help a lot for people to get on track on what's going on to this repo. Other than that, is to review PRs and answering questions in the ISSUE tab.

> there's a link to my blog in my profile

It seems like you know a lot of programming languages, maybe PR like #492 would be greatly appreciated!

You might also want to read through some guidelines like [MakingPackages](https://www.emacswiki.org/emacs/MakingPackages) from `EmacsWiki`, so you know what you should do to create a package. And make sure you don't break it while maintaining it. :)

Hope these information helps!

**Comment by tarsius** [comment]
@jcs090218 I just made you an "owner" of this organization.

In a second step I would like to step down as a owner myself.

**Comment by jcs090218** [comment]
Thanks! @tarsius

Feel free to leave this organization to me if you feel comfortable with it (or just step down as a owner)! I think we can keep this issue open since I am also **NOT** very active to this org, and maybe could find other potential maintainers! 😅 👍

**Comment by tarsius** [comment]
Great! Things have been running smoothly with you at the helm and I have no reason to doubt it will stay that way. If you find someone who wants to move this package forward that would be nice, but it seems to be doing fine in maintenance mode.

Cheers!

**Comment by theunixman** [comment]
I'm available to help maintain and possibly start adding features to this package. I've worked on my own private elisp modes and minor modes for awhile now, I've got [my (not well-organized) startup files](https://gitlab.com/tunixman/emacs-config) available for review as well. I've worked with text searching algorithms, NLP in general, and deep neural networks in the past too for what that's worth.

**Comment by jcs090218** [comment]
Awesome, it's great to have additional maintainers! Have you developed at least one package and published it to GNU Elpa or MELPA? I think it would be great if you have this experience in maintaining an elisp package. But for the bare minimum, you can start off by answering issues, reviewing PRs, etc.

**Comment by theunixman** [comment]
I've worked with local elisp packages, but I haven't uploaded anything yet. I'm happy to help with issues and PRs too.
Thanks!
